In [2]:
for i in range(1,6):
    if i == 3:
        break # Exit the loop when i is 3
        
    print(i)

1
2


In [3]:
for i in range (1,6):
    if i == 3:
        continue # Skip the current interation when i is 3
        
    print(i)

1
2
4
5


In [4]:
def some_function():
    pass # to be implemented later 

for i in range(1,6):
    if i % 2 ==0:
        pass # do nothing for even numbers
    else:
        print(i)

1
3
5


In [ ]:
# pop "pop" is a method of the listdata type in python
# It is used to remonve and return the element at a specified index from the list
# If no index is provided, it removes and returns the last element\
# pop is useful when you want to both remove an element and use it value


In [6]:
fruits = ['apple', 'bananna', 'orange', 'grapes']
removed_fruit = fruits.pop(1) # Remove and return the element of the index 1 (bananna)
print(removed_fruit)

bananna


In [9]:
# Quesion: what is pickling and unpickling in python?
''' pickling and unpickling are the process used to serialize and deseralize python objects, allowing you to convert 
complex data structures (such as lists, dictonaries, or cusom objects) ito a byte streams and viceversa'''

# - Pickling: Process of converting python object into byte stream so that it can be stored in a file or trnasferred over a network
# when you pickle an object, you are essentailly converting it into a binary format that can be easily sotred or transmitted

import pickle 
data = {'name': 'Tej', 'age': 35, 'city': 'Texas'}
#Pick the data and write it to a file:
with open('data.pickle', 'wb') as file:  # with statement is used with the file handaling to ensure that the file is 
    # properly closed after its suite finished execution, even if an exception occurs.
    pickle.dump(data, file) # the pickle.dump() function is used to serialize (pickle) the python object 'data' and 
    # write it to the file specified by the file "object"
    

In [11]:
### - Unpickling is the process to converting the byte stream back into a python object. It allow you to reconstruct
### the orginalpython object from the binary format

# the pickle moduel is also used fro unpickling
import pickle 

#unpickle the data from file
with open('data.pickle', 'rb') as file:
    loaded_data = pickle.load(file)
    
print(loaded_data)

{'name': 'Tej', 'age': 35, 'city': 'Texas'}


In [19]:
list_1 = [1,2,3] #define list_1
#using list concept and list function
# to multiply each value of list
list_2 = []
for i in list_1:
    x = i*3
    list_2.append(x)
    
list_2

[3, 6, 9]

In [21]:
## Move zero to the end of the list
list = [1, 0, 2, 0, 4, 0]

for item in list:
    if item == 0:
        list.remove(item)
        list.append(item)
        
list

[1, 2, 4, 0, 0, 0]

In [149]:
list = [0, 0, 1, 2, 3, 4,5]
for item in list:
    if item == 0:
        list.remove(item)
        list.append(item)
        
list

[1, 2, 3, 4, 5, 0, 0]

In [24]:
# how to print new line without using print
print('Hello world!',end = "")
print(' I am Tej.')   # We can add to lines without using print by using end parameter and the end as show in above



Hello world! I am Tej.


In [154]:
import numpy as np
n1 = np.zeros([5,5])
print(n1)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [25]:
import array as arr
my_arr = arr.array('i', [1, 3, 4, 6])
print(my_arr)
print(type(my_arr))

array('i', [1, 3, 4, 6])
<class 'array.array'>


In [26]:
my_dict = { 1: 'john',
          2 : 'raj',
          3 : [1, 2, 3]
          }
print(my_dict)

{1: 'john', 2: 'raj', 3: [1, 2, 3]}


In [29]:
def absolute_value(num):
    '''This function returns the absolute value of the entered numbers'''
    if num >=0:
        return num
    else:
        return -num
    
print(absolute_value(2))
print(absolute_value(-4))

2
4


In [30]:
def reverse(x):
    result = ""
    for i in x:
        result = i + result
        
    return result
x = "Hello!"
print("orginal string:", x)
print("reversed string:", reverse(x))

orginal string: Hello!
reversed string: !olleH


In [158]:
x = "Hello world"
print(x[::-1])

dlrow olleH


In [40]:
#fibonacci Series from recursion method
def fib(n):
    if n ==0:
        return 0
    elif n == 1:
        return 1
    else:
        return fib(n-2)+fib(n-1)
    
    
for n in range(10):
    print(fib(n), end = " ")
    

0 1 1 2 3 5 8 13 21 34 

In [162]:
def fab(n):
    if n == 0:
        return  0
    elif n == 1:
        return 1
    else:
        return fab(n-2)+fab(n-1)
    
for n in range(1,6):
    print(fab(n), end = ' ')


1 1 2 3 5 

In [41]:
## INbuilt reverse function

x = "Apple"
result = "".join(reversed(x))  # On wrapping the join() function around it will prepend each character to the empety string on whihc the dot operator is used
print(result)

elppA


In [42]:
x= "Apple"
print(x[::-1])'''# the argument for the step is -1, This will imply start from the last character (-1 is hte negative 
 index for the last string and take one step backward until the first character of the string'''


elppA


In [53]:
# python program to display all the prime number within the display

lower = 100
upper = 120

print("Prime number bewteen", lower, "and", upper, "are")

for num in range (lower, upper + 1):
    if i > 1:
        for i in range(2, num):
            if num % i ==0:
                break
        else:
            print(num)
        
    

Prime number bewteen 100 and 120 are
101
103
107
109
113


In [169]:
lower = 100
upper = 120

print("Prime number bewteen", lower, "and", upper, "are")

for num in range (lower, upper + 1):
    if i > 1:
        for i in range(2, num):
            if num % i ==0:
                break
        else:
            print(num)
        

Prime number bewteen 100 and 120 are
101
103
107
109
113


In [54]:
tuple = (4, 6, 7, "Jp", "hi")
print(tuple)

(4, 6, 7, 'Jp', 'hi')


In [56]:
tuple[0]  ##couple of handy builint method are count and index
len(tuple)

5

In [58]:
tup1 = (1, 3, "b")
tup2 = (2, 4, "c", "True")
print(tup1 + tup2)

(1, 3, 'b', 2, 4, 'c', 'True')


In [61]:
# how to initalize a 5*5 NumPy array with only zeroes?
import numpy as np
n1 = np.zeros((5,5))
print(n1)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [64]:
# What is pandas series?
# series is one-dimensional pandas data structure that support data of almost any type
import pandas as pd
data = ["1", 2, "Apple", 4.0, True]
series = pd.Series(data)
print(series)
print(type(series))

0        1
1        2
2    Apple
3      4.0
4     True
dtype: object
<class 'pandas.core.series.Series'>


In [70]:
# How to create data frame from lists
import pandas as pd
df = pd.DataFrame()  # need empty data frame
cars = ['Honda', 'Suzuki', 'Tesla', 'TATA']
bikes = ['KTM', 'Pulasr', 'Shine', 'RX']
df['cars']= cars  # addition of list as a individual columns in the dataframe
df['bikes'] = bikes #addition of list as a individual columns in the dataframe
print(df)

     cars   bikes
0   Honda     KTM
1  Suzuki  Pulasr
2   Tesla   Shine
3    TATA      RX


In [74]:
# how to create dataframe from dictonary

df = pd.DataFrame()
cars = ['Honda', 'Suzuki', 'Tesla', 'TATA']
bikes = ['KTM', 'Pulasr', 'Shine', 'RX']

d = {'cars':cars, 'bikes':bikes} # pass the argument to the dataframe
df = pd.DataFrame(d) #
print(df)
 


     cars   bikes
0   Honda     KTM
1  Suzuki  Pulasr
2   Tesla   Shine
3    TATA      RX


In [75]:
# how to combine DataFrames using join function 
df = pd.DataFrame()
data1 = {'Name': ['Raj', 'John', 'Hari', 'Tej'],
        'Salary': [5000, 1000, 3000, 6000]}
df1 = pd.DataFrame(data1)

data2 = {'Name': ['Raj', 'Hari', 'Rose', 'Prem'],
        'Cars': ["Tesla", 'Suzuki', 'Ferrari', 'TATA']}
df2 = pd.DataFrame(data2)
Join_data = df1.set_index('Name').join(df2.set_index('Name'))
print(Join_data)


      Salary    Cars
Name                
Raj     5000   Tesla
John    1000     NaN
Hari    3000  Suzuki
Tej     6000     NaN


In [170]:
data1 = {'Name': ['Raj', 'John', 'Hari', 'Tej'],
        'Salary': [5000, 1000, 3000, 6000]}
data2 = data2 = {'Name': ['Raj', 'Hari', 'Rose', 'Prem'],
        'Cars': ["Tesla", 'Suzuki', 'Ferrari', 'TATA']}
joined = df1.set_index("Name").join(df2.set_index("Name"))
print(joined)

      Salary    Cars
Name                
Raj     5000   Tesla
John    1000     NaN
Hari    3000  Suzuki
Tej     6000     NaN


In [78]:
# Merging of data in data frame
df = pd.DataFrame()
data1 = {'Name': ['Raj', 'John', 'Hari', 'Tej'],
        'Salary': [5000, 1000, 3000, 6000]}
df1 = pd.DataFrame(data1)

data2 = {'Name': ['Raj', 'Hari', 'Rose', 'Prem'],
        'Cars': ["Tesla", 'Suzuki', 'Ferrari', 'TATA']}
df2 = pd.DataFrame(data2)
Merge_data = pd.merge(df1,df2, on = 'Name', how = 'inner')  # on = 'Name' column specefies the merge on name column
# The 'inner' keeps the rows only matching with name
print(Merge_data)  

   Name  Salary    Cars
0   Raj    5000   Tesla
1  Hari    3000  Suzuki


In [88]:
import pandas as pd
#Sample data frame

data1 = {'Name': ['Raj', 'John', 'Hari', 'Tej'],
        'Salary': [1000, 2000, 3000, 4000],
        'Department': ['IT', 'Finance', 'Physics', 'Biology']
        }
df= pd.DataFrame(data1)
#print(df)
#set the 'Name column as index'
df.set_index('Name', inplace = True)
print(df)

      Salary Department
Name                   
Raj     1000         IT
John    2000    Finance
Hari    3000    Physics
Tej     4000    Biology


In [90]:
Tej_data = df.loc['Tej']
print(Tej_data)

Salary           4000
Department    Biology
Name: Tej, dtype: object


In [100]:
import numpy as np
x = np.array([3, 5, 10, 300, 4])
x_mean= x.mean()
x_std = x.std()
x_median = np.median(x)  # no median value is np arrays
print("x_mean is:", x_mean)
print("x_std is:", x_std)
print('x_median is:', x_median)

x_mean is: 64.4
x_std is: 117.82461542479145
x_median is: 5.0


In [101]:
import numpy as np
x = np.array([3, 5, 10, 300, 4])
print(np.mean(x))
print(np.std(x))
print(np.median(x))

64.4
117.82461542479145
5.0


In [104]:
x = "Apple"
print(x.lower())

apple


In [106]:
# How do you get a list of all keys in a dictionary
data1 = {'Name': ['Raj', 'John', 'Hari', 'Tej'],
        'Salary': [1000, 2000, 3000, 4000],
        'Department': ['IT', 'Finance', 'Physics', 'Biology']
        }
data1.keys()

dict_keys(['Name', 'Salary', 'Department'])

In [109]:
x = 'apple'
print(x.capitalize())

Apple


In [113]:
list = [0, 1, 3, 4, 6, 9]
list.insert(3,6)
print(list)


[0, 1, 3, 6, 4, 6, 9]


In [179]:

list1 = [1, 3, 3, 5, 7]
N_list = list(set(list1))
print(N_list)


TypeError: 'list' object is not callable

In [180]:
list = [1,3,3,5,7]
N_list = []
[N_list.append(x) for x in list if x not in N_list]
print(N_list)

[1, 3, 5, 7]


In [114]:
#Recurssion

def factorial(n):
    if n == 0 or n == 1:
        return 1
    else:
        return n * factorial(n-1)
    
print(factorial(5))

120


In [120]:
list = [1, 3, 6, 7, 8, 10]
even_list = [x for x in list if x % 2 == 0]
print(even_list)

[6, 8, 10]


In [136]:
A_list = [ i for i in range(5, 10)]
print(A_list)
len(A_list)

[5, 6, 7, 8, 9]


5

In [135]:
n = 10
print(type(n))
New_n = str(n)
print(type(New_n))

<class 'int'>
<class 'str'>


In [140]:
letters = ('A , B C') # list dosnot works fro list  - only string

n = letters.split(',')
print(n)

['A ', ' B C']


In [181]:
str = "Hello"
byte_data = bytes(str, encoding = 'utf8')
print(byte_data)

b'Hello'


# Can you denote the working of the bool() function with examples?

The bool() function in python returns either logical True or False.
It can output anythings else apart from the logical operation

In [146]:
a = "Hello"
b = 15
c = 0
sample_list = []
print(bool(a))
print(bool(b))
print(bool(c))
print(bool(sample_list))

True
True
False
False


In [1]:
my_list = [1,2,3,4,5]
result = my_list[-3:-1]
print(result)

[3, 4]


In [4]:
# 03_letter_explosion.py
print('{2}, {1}, {0}'.format(*'abc'))

c, b, a
